"""update embedding dimension to 1024

Revision ID: 291fa939d79c
Revises: 7a0e85d98abb
Create Date: 2026-07-18 18:15:32.461041

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '291fa939d79c'
down_revision: Union[str, Sequence[str], None] = '7a0e85d98abb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Drop the old HNSW index first (required before altering vector column)
    op.drop_index(
        op.f('ix_embeddings_vector_hnsw'), 
        table_name='embeddings', 
        postgresql_ops={'vector': 'vector_cosine_ops'}, 
        postgresql_with={'m': '16', 'ef_construction': '64'}, 
        postgresql_using='hnsw'
    )
    
    # 2. Alter the vector column to the NEW dimension (1024 for NVIDIA, or 768 for Nomic)
    op.alter_column('embeddings', 'vector', type_=Vector(1024))
    
    # 3. Recreate the HNSW index with the new dimension
    op.create_index(
        op.f('ix_embeddings_vector_hnsw'), 
        'embeddings', 
        ['vector'], 
        unique=False, 
        postgresql_ops={'vector': 'vector_cosine_ops'}, 
        postgresql_with={'m': '16', 'ef_construction': '64'}, 
        postgresql_using='hnsw'
    )
    
    # Note: The chunk_metadata constraint drop/create was likely a false positive from autogenerate.
    # We omit it here to keep the migration clean and focused only on the vector dimension.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Drop the new HNSW index
    op.drop_index(
        op.f('ix_embeddings_vector_hnsw'), 
        table_name='embeddings', 
        postgresql_ops={'vector': 'vector_cosine_ops'}, 
        postgresql_with={'m': '16', 'ef_construction': '64'}, 
        postgresql_using='hnsw'
    )
    
    # 2. Revert the vector column back to 768
    op.alter_column('embeddings', 'vector', type_=Vector(768))
    
    # 3. Recreate the original HNSW index
    op.create_index(
        op.f('ix_embeddings_vector_hnsw'), 
        'embeddings', 
        ['vector'], 
        unique=False, 
        postgresql_ops={'vector': 'vector_cosine_ops'}, 
        postgresql_with={'m': '16', 'ef_construction': '64'}, 
        postgresql_using='hnsw'
    )
    # ### end Alembic commands ###