"""add_session_id_to_documents

Revision ID: c56ae6eebc1f
Revises: 561d904e543f
Create Date: 2026-07-19 18:18:06.115324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c56ae6eebc1f'
down_revision: Union[str, Sequence[str], None] = '561d904e543f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('chunk_metadata_chunk_id_key'), 'chunk_metadata', type_='unique')
    op.add_column('documents', sa.Column('session_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_documents_session_id'), 'documents', ['session_id'], unique=False)
    op.create_foreign_key(None, 'documents', 'chat_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_embeddings_vector_hnsw'), table_name='embeddings', postgresql_ops={'vector': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_embeddings_vector_hnsw'), 'embeddings', ['vector'], unique=False, postgresql_ops={'vector': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_index(op.f('ix_documents_session_id'), table_name='documents')
    op.drop_column('documents', 'session_id')
    op.create_unique_constraint(op.f('chunk_metadata_chunk_id_key'), 'chunk_metadata', ['chunk_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
