# schemas/rag.py

"""
Phase 7: Complete RAG Pipeline Schemas

Defines Pydantic V2 data structures for source attribution, reranking results,
constructed context windows, system prompt payloads, and grounded RAG responses.
"""

from __future__ import annotations
import uuid
import datetime
from typing import Literal
from pydantic import BaseModel, Field, ConfigDict


class SourceAttribution(BaseModel):
    """
    Structured evidence metadata for source attribution and citations.
    """
    model_config = ConfigDict(from_attributes=True)

    document_id: uuid.UUID = Field(..., description="UUID of parent document")
    chunk_id: uuid.UUID = Field(..., description="UUID of specific chunk")
    filename: str = Field(..., description="Original filename of parent document")
    chunk_index: int = Field(..., description="Index position of chunk in document")
    page_number: int | None = Field(default=None, description="Page number if applicable")
    section: str | None = Field(default=None, description="Section heading if available")
    heading: str | None = Field(default=None, description="Document heading if available")
    similarity_score: float = Field(..., description="Normalized similarity score [0.0 - 1.0]")
    content_snippet: str = Field(..., description="Truncated content snippet for UI preview")


class RerankedResult(BaseModel):
    """
    Candidate chunk after passing through the Re-ranking Service layer.
    """
    model_config = ConfigDict(from_attributes=True)

    original_rank: int = Field(..., description="Rank prior to reranking")
    new_rank: int = Field(..., description="Rank position after reranking")
    initial_score: float = Field(..., description="Initial vector similarity score")
    reranked_score: float = Field(..., description="Adjusted score after metadata quality reranking")
    chunk_id: uuid.UUID = Field(..., description="UUID of chunk")
    document_id: uuid.UUID = Field(..., description="UUID of document")
    filename: str = Field(..., description="Filename")
    content: str = Field(..., description="Full text content of chunk")
    token_count: int = Field(default=0, description="Token length of chunk")
    metadata: dict | None = Field(default=None, description="Metadata dictionary")


class BuiltContext(BaseModel):
    """
    Clean, deduplicated, token-bounded context ready for prompt injection.
    """
    model_config = ConfigDict(from_attributes=True)

    context_text: str = Field(..., description="Formatted string containing all context chunks")
    total_tokens: int = Field(..., description="Total estimated token count of context_text")
    chunk_count: int = Field(..., description="Total number of chunks included in context")
    sources: list[SourceAttribution] = Field(default_factory=list, description="Associated source attributions")


class PromptPayload(BaseModel):
    """
    Fully assembled prompt payload containing system instructions, context, and history.
    """
    model_config = ConfigDict(from_attributes=True)

    system_prompt: str = Field(..., description="System instructions including grounding constraints")
    context_text: str = Field(..., description="Injected context section")
    user_query: str = Field(..., description="User's natural language question")
    formatted_messages: list[dict] = Field(default_factory=list, description="Messages payload ready for OpenAI SDK")


class RAGResponse(BaseModel):
    """
    Final output model of the Phase 7 Complete RAG Pipeline.
    """
    model_config = ConfigDict(from_attributes=True)

    answer: str = Field(..., description="Grounded response text generated by LLM")
    is_grounded: bool = Field(..., description="True if answer was generated from retrieved context")
    fallback_used: bool = Field(..., description="True if system fell back to ungrounded base LLM")
    sources: list[SourceAttribution] = Field(default_factory=list, description="List of source attributions used")
    context_tokens: int = Field(default=0, description="Token count of injected context")
    total_latency_ms: float = Field(..., description="End-to-end RAG pipeline latency in ms")
    search_latency_ms: float = Field(default=0.0, description="Vector search latency in ms")
    rerank_latency_ms: float = Field(default=0.0, description="Reranking latency in ms")
    generation_latency_ms: float = Field(default=0.0, description="LLM inference latency in ms")
